# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_identifyingcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField()),
                ('info', models.CharField(max_length=500)),
            ],
        ),
    ]
