# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='info',
            field=models.CharField(max_length=600),
        ),
    ]
