# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171016_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='info',
            field=models.TextField(),
        ),
    ]
