# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171022_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('solution_id', models.IntegerField()),
                ('level_id', models.IntegerField()),
                ('info', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
