# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='id',
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
