# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_user_solution_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='solution_list',
            new_name='solution_dict',
        ),
    ]
