# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20171029_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
