# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_solution_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='std_solution_id',
            field=models.IntegerField(default=-1),
        ),
    ]
